### ISSUE TITLE
Potential typo in README.md

### ISSUE THREAD

**Issue by btwiuse** [buildbarn/bb-deployments#11]
Hi, I'm trying to setup a working buildbarn cluster following the instructions provided in README.md.

I'm a little wary about the first line from this part:
```
build:mycluster --bes_backend=grpc://fill-in-the-frontend-service-hostname-here:8985
build:mycluster --bes_results_url=http://fill-in-the-browser-service-hostname-here/build_events/bb-event-service/
build:mycluster --remote_executor=grpc://fill-in-the-frontend-service-hostname-here:8980
build:mycluster --remote_instance_name=remote-execution
```
According to [bazel document](https://docs.bazel.build/versions/master/build-event-protocol.html#the-build-event-service), `--bes_backend` should point to bb-event-service, not bb-frontend-service. Is my understanding correct?

**Comment by EdSchouten** [comment]
You are entirely correct! Could you send a PR to get that fixed? Thanks!

**Comment by btwiuse** [comment]
Sure, I'll do it now
