### ISSUE TITLE
docker-compose deployment is broken for docker on macOS

### ISSUE THREAD

**Issue by amarshat** [buildbarn/bb-deployments#14]
With docker on macOS, the idea about sharing `/worker/runner` as a unix-socket across `worker` and `runner` fails with the error 
`gRPC server failure: rpc error: code = Unknown desc = Failed to create listening socket for "/worker/runner": listen unix /worker/runner: bind: file name too long`

This appears to be due to this:  https://github.com/moby/moby/issues/23545#issuecomment-226144475

The `bb_runner`'s socket directory is shared via mount, and in macOS that is consumed as full path. This leads to size overflow. Can we run `runner` and `worker` on the same container?

**Comment by EdSchouten** [comment]
I think we should leave the docker-compose deployment as is, as the current model should remain the canonical way Buildbarn is deployed. The Docker/Moby folks should just fix the issue linked.

That said, as a workaround, you could simply change the bb-runner gRPC server configuration and the bb-worker gRPC client configuration to use TCP. Just take a look at [this schema](https://github.com/buildbarn/bb-storage/blob/master/pkg/proto/configuration/grpc/grpc.proto) and some of the other configuration files to figure out how that can be set up.
