### ISSUE TITLE
Failed to run command: Cannot find executable "python3" in search paths ""

### ISSUE THREAD

**Issue by AnubisYe** [buildbarn/bb-deployments#143]
When I compile chromium, I get the following error
<img width="1090" alt="image" src="https://github.com/user-attachments/assets/a332f298-edd6-4cfb-a00b-787a67a28434">
action detail:
<img width="1770" alt="image" src="https://github.com/user-attachments/assets/975e660b-b9c7-4c07-953b-2955b4c7e697">
**It is true that the python path is not in the Input files.** 
How can I solve this problem, or  use the python3 of the runner environment?

**Comment by EdSchouten** [comment]
I'd say, `kubectl exec` into the runner container to check whether `python3` is available somewhere on the file system. Then rerun Bazel with `--action_env=PATH=/directory/where/python3/executable/lives`.

**Comment by AnubisYe** [comment]
> I'd say, `kubectl exec` into the runner container to check whether `python3` is available somewhere on the file system. Then rerun Bazel with `--action_env=PATH=/directory/where/python3/executable/lives`.
> 
> Edit: Oh, wait. reclient. In that case you need to pass in some other command line flag/config option. You get the idea. :-)

Thanks 
Finally, I modified [local_runner.go](https://github.com/buildbarn/bb-remote-execution/blob/9850e82ad7d875aa2ab183a5a08d79725c10fa16/pkg/runner/local_runner.go#L258) to return python path in runner env when executing python

**Comment by EdSchouten** [comment]
Why would you need to do that? reclient should just set PATH properly.

**Comment by AnubisYe** [comment]
> Why would you need to do that? reclient should just set PATH properly.

https://github.com/bazelbuild/reclient/blob/main/docs/cmd-line-flags.md

which flag should I set...

**Comment by EdSchouten** [comment]
`-env_var_allowlist PATH` maybe?
