### ISSUE TITLE
why the ac and its output stored to different server when use bb-storage as a frontend

### ISSUE THREAD

**Issue by danni-yan** [buildbarn/bb-deployments#149]
I'm using [bazel-remote](https://github.com/buchgr/bazel-remote/) for cache server now. And I want to extend one cache node to many. So I add a bb-storage as a frontend.

Normally, the ac and cas(output) shoud be stored by one server. But I find out that the ac and cas may be stored separately.

so I trid bb-storage as cache server. seems problem is gone. is there any configuration to note?

Here is my configration.

```
{
  grpcServers: [{
    listenAddresses: [':8980'],
    authenticationPolicy: { allow: {} },
  }],
  maximumMessageSizeBytes: 2 * 1024 * 1024,
  contentAddressableStorage: {
    backend: {
      sharding: {
        hashInitialization: 11946695773637837490,
        shards: [
          {
            backend: { grpc: { address: '127.0.0.1:9091' } },
            weight: 1,
          },
          {
            backend: { grpc: { address: '127.0.0.1:9092' } },
            weight: 1,
          },
        ],
      },
    },
    getAuthorizer: { allow: {} },
    putAuthorizer: { allow: {} },
    findMissingAuthorizer: { allow: {} },
  },
  actionCache: {
    backend: {
      completenessChecking: {
        backend: {
          sharding: {
            hashInitialization: 14897363947481274433,
            shards: [
              {
                backend: { grpc: { address: '127.0.0.1:9091' } },
                weight: 1,
              },
              {
                backend: { grpc: { address: '127.0.0.1:9092' } },
                weight: 1,
              },
            ],
          },
        },
        maximumTotalTreeSizeBytes: 64 * 1024 * 1024,
      },
    },
    getAuthorizer: { allow: {} },
    putAuthorizer: { allow: {} },
  },
}

```

**Comment by EdSchouten** [comment]
When setting up an Action Cache & Content Addressable Storage, there needs to be some system in place that ensures that Action Cache entries that are returned by GetActionResult() only refer to objects that actually exist in the Content Addressable Storage. At the same time, it should bump the TTL on these objects. Buildbarn implements this logic as part of `completenessChecking` which you have in the config above.

Buildbarn differs from bazel-remote, in that it explicitly requires you to enable `completenessChecking`. The reason being that the exact place where it needs to be enabled depends on your setup. Simple setups that only consist of a single bb-storage node (without any frontend processes) can stack `completenessChecking` directly on top of the local disk-based storage backend. Larger sharded setups need to enable it on the frontends. Not on the individual storage nodes, as those don't have a holistic view of the Content Addressable Storage.

bazel-remote has something like `completenessChecking` turned on by default. You need to explicitly launch it with `--disable_grpc_ac_deps_check` if you want to launch it in such a way that it can be used as a single shard in a shared setup.

**Comment by danni-yan** [comment]
Nice! 

I havent read the code but through the deployments, the bb-storage binary can be used as a frontend and also a storage server. I'm wonder how you do that. 

And what is the load balancing policy. When I add new cache server instances, will some caches become invalid and need to be re-uploaded?

**Comment by EdSchouten** [comment]
> I havent read the code but through the deployments, the bb-storage binary can be used as a frontend and also a storage server. I'm wonder how you do that.

There's basically a bunch of storage backends that are all written in a stackable way. So in the case of the frontend binary, we configure it to not be backed by actual storage, but by a gRPC client that simply forwards the requests.

> And what is the load balancing policy. When I add new cache server instances, will some caches become invalid and need to be re-uploaded?

Yes. When you add more shards, the sharding function completely changes, causing old objects to become inaccessible and any in-flight builds to fail.

However, you can work around this by (ab)using the 'mirrored'. Namely, create a config like this:
```
{ mirrored: {
  backendA: { sharding: { /* the old sharding topology */ } },
  backendB: { sharding: { /* the new sharding topology */ } },
  ...
} }
```
After you've rolled that out and have given it some time to settle, you can remove the `mirrored` setup, only leaving behind the new `sharding` setup.

**Comment by danni-yan** [comment]
Thank you so much for the reply! buildbarn is an awesome project！
