### ISSUE TITLE
Build Event service is not added in bare deployment script and seeing errors when i run manually

### ISSUE THREAD

**Issue by praveenkanna** [buildbarn/bb-deployments#2]
Hello @EdSchouten 

I tried with [example](https://github.com/bazelbuild/examples/tree/master/cpp-tutorial/stage3) with build barn to check how it works and all. 

First thing I see is there is no build even service deployment is in the bare run.sh, so I manually deployed using below command : 

```
../../bb-event-service/bazel-bin/cmd/bb_event_service/linux_amd64_pure_stripped/bb_event_service -blobstore-config blobstore-storage-clients.conf -web.listen-address localhost:7983

```
I picked the port as in the docker-compose file. 

And below are the build options I chose in my bazelrc file: 

```
build --experimental_strict_action_env --spawn_strategy=remote --genrule_strategy=remote --strategy=Javac=remote --strategy=Closure=remote --remote_executor=localhost:8980

build --jobs=8 --remote_instance_name=local --bes_backend=localhost:7984 --bes_results_url=http://localhost:7984/build_events/bb-event-service/
```
I am able to see the action results and able to view in browser url (http://localhost:7984/action/local/0488e607fb8389d0b3f92e96973f009f2347c8aec383e759a19877f8e93721c9/142/), and log here:

```
-bash-4.2$ 2019/04/30 15:11:16 Action: http://localhost:7984/action/local/73104ef5a33e79746cf6271dc47e4638ed2404fe24a9c2cf383029237c456ed5/142/
2019/04/30 15:11:16 ExecuteResponse: result:<output_files:<path:"bazel-out/k8-fastbuild/bin/main/_objs/hello-world/hello-world.pic.d" digest:<hash:"39350f1b30c43496f8193580cb062a17bef2f91ebe1d02c5e6fae17632866b69" size_bytes:8486 > > output_files:<path:"bazel-out/k8-fastbuild/bin/main/_objs/hello-world/hello-world.pic.o" digest:<hash:"89b366c59d8d24860bc790d46da131bbfa1e7e8edb7b1306b8243b1b75896145" size_bytes:6632 > > > message:"Action details (cached result): http://localhost:7984/action/local/73104ef5a33e79746cf6271dc47e4638ed2404fe24a9c2cf383029237c456ed5/142/" 
2019/04/30 15:11:16 Action: http://localhost:7984/action/local/371b1a71b0e05eea276bc63598b440b6e79dde745bca2c821c4544a53d9bd4b1/142/
2019/04/30 15:11:17 ExecuteResponse: result:<output_files:<path:"bazel-out/k8-fastbuild/bin/main/hello-world" digest:<hash:"634dad4e327c62c3d517792d73e8bcc3219b74f495a5c72496fc25b741d23f43" size_bytes:13920 > is_executable:true > > message:"Action details (cached result): http://localhost:7984/action/local/371b1a71b0e05eea276bc63598b440b6e79dde745bca2c821c4544a53d9bd4b1/142/"
```

I'm having issues uploading build event protocol results, I see the error in the client is :

```
ERROR: The Build Event Protocol upload failed: INTERNAL: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
INFO: Partial Build Event Protocol results may be available at http://localhost:7983/build_events/local/5c6d5f8e-5277-43a0-ba6d-3a69e1cc2c18
```

Please let me know how I can get rid of this error and make it working and able to see the results in the browser. 

(And) 

I have one more question that we already have a remote cache server already (nginx), Is there any way we can just use browser and build event protocol rather than using all the build barn bundle and execute the build using the current existing remote cache. If so could you please forward me the process of how I can achieve that would be more appreciated.

**Comment by EdSchouten** [comment]
Hi there! I've just extended the example deployment to also incorporate the bb-event-service.

> I have one more question that we already have a remote cache server already (nginx), Is there any way we can just use browser and build event protocol rather than using all the build barn bundle and execute the build using the current existing remote cache. If so could you please forward me the process of how I can achieve that would be more appreciated.

Yes. You should be able to fire up bb-browser / bb-event-service processes that have a blobstore.conf that looks like this:

```
content_addressable_storage {
  grpc {
    endpoint: "http://the-cache/"
  }
}
action_cache {
  grpc {
    address: "http://the-cache/"
  }
}
```

**Comment by EdSchouten** [comment]
That's a bit ugly about bb-browser: it currently has to be started either through Docker or using the right working directory in the bb-browser source tree to be able to find its HTML templates, hence the `cd` in `run.sh`.

This should be resolved as soon as https://github.com/buildbarn/bb-browser/issues/4 is fixed. Once that work lands, bb-browser will have all of the assets served over HTTP built into the binary.

**Comment by EdSchouten** [comment]
Yeah, you need to run it from within `cmd/bb_browser`.

**Comment by praveenkanna** [comment]
> Yeah, you need to run it from within `cmd/bb_browser`.

Nope, still same:

```
bash-4.2$ pwd
/home/praveen/buildbarn/projects/bb-browser/bazel-bin/cmd/bb_browser
-bash-4.2$ ./linux_amd64_pure_stripped/bb_browser -blobstore-config blobstore.conf -web.listen-address localhost:7984
2019/05/03 08:22:06 Failed to parse templates: html/template: pattern matches no files: `templates/*`
```
even tried the same inside linux folder no change.

**Comment by EdSchouten** [comment]
Please take some time to read up on what `run.sh` does. As you can see, it runs `bb_browser` from within `cmd/bb_browser`, whereas you are trying to run it from within `bazel-bin/cmd/bb_browser`.

**Comment by praveenkanna** [comment]
hahaha... I don't even understand how I missed that. Thanks, it worked fine.

**Comment by praveenkanna** [comment]
Hey @EdSchouten , 

It worked fine for the example code, but coming to the larger code it is giving an error:

```
(11:08:42) ERROR: The Build Event Protocol upload failed: RESOURCE_EXHAUSTED: RESOURCE_EXHAUSTED: grpc: received message larger than max (5012258 vs. 4194304)
(11:08:42) INFO: Partial Build Event Protocol results may be available at http://bazel-browser:7984/build_events/bb-event-service/d9143236-ad42-40a1-80c1-b8805b1c3523
(11:10:35) ERROR: io.grpc.StatusException: RESOURCE_EXHAUSTED: grpc: received message larger than max (5012258 vs. 4194304)

```
Any idea why I'm seeing this and Is there any way we can increase the limit?

**Comment by qaisjp-stripe** [comment]
> Hey @EdSchouten ,
> 
> It worked fine for the example code, but coming to the larger code it is giving an error:
> 
> ```
> (11:08:42) ERROR: The Build Event Protocol upload failed: RESOURCE_EXHAUSTED: RESOURCE_EXHAUSTED: grpc: received message larger than max (5012258 vs. 4194304)
> (11:08:42) INFO: Partial Build Event Protocol results may be available at http://bazel-browser:7984/build_events/bb-event-service/d9143236-ad42-40a1-80c1-b8805b1c3523
> (11:10:35) ERROR: io.grpc.StatusException: RESOURCE_EXHAUSTED: grpc: received message larger than max (5012258 vs. 4194304)
> ```
> 
> Any idea why I'm seeing this and Is there any way we can increase the limit?

Solution is here: https://github.com/bazelbuild/bazel/issues/12050

**Comment by qaisjp** [comment]
> Hey @EdSchouten ,
> 
> It worked fine for the example code, but coming to the larger code it is giving an error:
> 
> ```
> (11:08:42) ERROR: The Build Event Protocol upload failed: RESOURCE_EXHAUSTED: RESOURCE_EXHAUSTED: grpc: received message larger than max (5012258 vs. 4194304)
> (11:08:42) INFO: Partial Build Event Protocol results may be available at http://bazel-browser:7984/build_events/bb-event-service/d9143236-ad42-40a1-80c1-b8805b1c3523
> (11:10:35) ERROR: io.grpc.StatusException: RESOURCE_EXHAUSTED: grpc: received message larger than max (5012258 vs. 4194304)
> ```
> 
> Any idea why I'm seeing this and Is there any way we can increase the limit?

The solution for this is here: https://github.com/bazelbuild/bazel/issues/12050 / https://github.com/buildbuddy-io/buildbuddy/commit/7cd6929ac9663439d63d74ab201fca72cc3b9054
