### ISSUE TITLE
Support Kubernetes clusters where you don't have root

### ISSUE THREAD

**Issue by zoidyzoidzoid** [buildbarn/bb-deployments#21]
I ended up getting around this by using a subPath.

The error happens because a non-root user doesn't have the necessary rights to do `chmod 0777 /worker`

```
        command:
        - sh
        - -c
        - mkdir -pm 0777 /worker/build && mkdir -pm 0700 /worker/cache && chmod 0777 /worker
```

I thought the following might help, but I don't think it affects empty dirs:

```
pod.spec.securityContext.fsGroup
```

**Comment by moroten** [comment]
Closing as stale. Please comment if you still have the problem.
