### ISSUE TITLE
docker-compose: Race between bb-runner-installer and the runner container

### ISSUE THREAD

**Issue by EdSchouten** [buildbarn/bb-deployments#28]
It is possible for the runner container to fail to start, due to this error:
```
runner-ubuntu16-04_1  | [FATAL tini (7)] exec /bb/bb_runner failed: Text file busy
```

This may happen if the runner container is started while the bb_runner binary is still being copied.

Cc @asuffield @finn-ball

**Comment by EdSchouten** [comment]
Fixed in https://github.com/buildbarn/bb-deployments/commit/c023446196ed746bfd36a2fde7e648b40834c314

**Comment by cphang99** [comment]
This appears to still be present: https://gitlab.com/remote-apis-testing/remote-apis-testing/-/issues/95

**Comment by moroten** [comment]
Fixed in https://github.com/buildbarn/bb-remote-execution/commit/4dfbe5b09d1c21f888e4d9022b73123de1b8a180 and c023446196ed746bfd36a2fde7e648b40834c314.
