### ISSUE TITLE
What protocol the frontend service is using?

### ISSUE THREAD

**Issue by llegolas** [buildbarn/bb-deployments#3]
I'm trying to expose the frontend service to the outside world from OpenShift cluster with the assumption that it is gRPC (over HTTP/2) is that correct or it is custom protocol which needs tcp tunnel?

**Comment by mickael-carl** [comment]
Hi! Nice to hear you're giving this a try! Everything should be HTTP/2 based so your assumption is likely correct. Could you give it a try and let us know how it turned out? We're also interested to see how users are setting up Buildbarn, and we could further document those usecases.

**Comment by llegolas** [comment]
It wasn't trivial to get it working on OpenShift. The main problem was that the default ingress controller ("router" in OpenShift terms) is haproxy which with the version used is supporting HTTP/2 only on the front side so we went with nginx  based additional ingress controller and route labels to do the sharding.
I can share my docs if someone else needs them but it will be longish post I'm not sure fits this thread.
