### ISSUE TITLE
bb_worker issue when working with docker-compose

### ISSUE THREAD

**Issue by dhillondeep** [buildbarn/bb-deployments#39]
I am trying to use `docker-compose` deployment and I am getting this error:
```
runner-installer_1    | /bb
worker-ubuntu16-04_1  | 2020/07/27 04:41:42 Runner is not ready yet: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /worker/runner: connect: no such file or directory"
```

I have not made any changes to the repo.

**Comment by EdSchouten** [comment]
You see that warning when bb-worker starts before bb-scheduler is online. It's safe to ignore those warnings, as long as they don't keep on repeating.
