### ISSUE TITLE
BB-deployments on Ubuntu Focal 20.04

### ISSUE THREAD

**Issue by mihaigalos** [buildbarn/bb-deployments#50]
I'm having trouble using remote execution on `ubuntu focal 20.04`. The same works flawlessly on `ubuntu bionic 18.04`.
Bazel version is `3.3.0`.

Here are the logs from my execution:
[logs.txt](https://github.com/buildbarn/bb-deployments/files/5524158/logs.txt)

What am I doing wrong?

**Comment by finn-ball** [comment]
Is docker installed?

**Comment by finn-ball** [comment]
`2020/11/11 13:14:07 could not download Bazel: HTTP GET https://releases.bazel.build/3.3.0/release/bazel-3.3.0-linux-x86_64 failed: Get https://releases.bazel.build/3.3.0/release/bazel-3.3.0-linux-x86_64: dial tcp: lookup releases.bazel.build on 160.50.252.2:53: no such host`

Are you able to connect to that address and download the file from your machine?

**Comment by mihaigalos** [comment]
Yes, I have `bazelisk` on my machine and  `3.3.0` inside the `.bazelversion`.
Is there any way to temporarily disable bazelisk? - seems traffic doesn't get past the corporate firewall for some reason.

Tried manually downloading the binary and remotely executing using it, same behavior - seems it somehow defaults to  `bazelisk`:
```bash
/tmp/tmp.QRjfMrXK0Z/bazel-3.3.0-linux-x86_64 build --config=mycluster-ubuntu16-04 @abseil-hello//:hello_main 
...
could not download Bazel: HTTP GET https://releases.bazel.build/3.3.0/release/bazel-3.3.0-linux-x86_64 failed: Get https://releases.bazel.build/3.3.0/release/bazel-3.3.0-linux-x86_64: dial tcp: lookup releases.bazel.build on 160.50.252.2:53: no such host 
```

**Comment by finn-ball** [comment]
Try removing bazelisk and just install bazel on that machine:
https://github.com/bazelbuild/bazel/releases/tag/3.3.0

That may help. If it doesn't you may want to raise this as an issue with bazeltoolchains:
https://github.com/bazelbuild/bazel-toolchains 

As it's failing in their script.

Either way, this isn't a buildbarn issue and so we should probably close this ticket.

**Comment by mihaigalos** [comment]
I still have the same behavior after:
```bash
sudo apt remove --purge bazelisk
dpkg --list | grep bazelisk # nothing listed
```

Performed a `clean --async` as well.

Does the executor somehow try to somehow download bazel?!

**Comment by finn-ball** [comment]
I don't have time today to look deeply into this but I would say there is a high chance that bazelisk is being used by the bazel-toolchains project:

https://github.com/bazelbuild/bazel-toolchains/search?q=bazelisk

**Comment by mihaigalos** [comment]
would it help to just inject the `http_proxy` into the running docker? - if yes, is it in the `docker-compose/docker-compose.yaml` or somewhere else?

**Comment by moroten** [comment]
Closing as stale.
