### ISSUE TITLE
Error when trying to use remote cache

### ISSUE THREAD

**Issue by Alexander-Scott** [buildbarn/bb-deployments#51]
Hi, after setting up builbarn via `./run.sh`, attempting to perform bazel build with the `--remote_cache` flag pointing to the instance returns the following error:

```
INFO: Invocation ID: 627d373c-0f1f-44d6-93c6-0dcbd09812a3
ERROR: --remote_upload_local_results is set, but the current account is not authorized to write local results to the remote cache.
```

Any ideas what could be causing this? The part of the code which generates this error in bazel is [here](https://github.com/bazelbuild/bazel/blob/f8e45f4a3a622aefa43069757ee49c1f97b15544/src/main/java/com/google/devtools/build/lib/remote/RemoteServerCapabilities.java#L247).

**Comment by EdSchouten** [comment]
Hi Alexander,

The example deployments that we provide are purely intended to be used for remote execution, it seems. When you want to do plain remote caching, you need to allow write access to the Action Cache by the clients. This should typically be disabled in the case of remote execution, as it would allow clients to poison the cache.

You can enable write access to the Action Cache by adding a line like this to the bb-frontend configuration. By adding the empty string to the list of instance name prefixes, you allow write access for every `--remote_instance_name`.
```
allowAcUpdatesForInstanceNamePrefixes: [''],
```

**Comment by Alexander-Scott** [comment]
Many thanks for your fast response, that seemed to solve it. I should read the documentation more carefully next time! Thanks :)
