### ISSUE TITLE
Update the examples to use the current docker Images

### ISSUE THREAD

**Issue by charlesoconor** [buildbarn/bb-deployments#55]
The example k8s doesn't work with the newer version of the docker images that have been published. It would be great to get an updated example to how to work with the newer images. Thanks!

**Comment by pseymournutanix** [comment]
The config map files aren't correct even for the versions of the images in the current k8s manifests.

The storage pod for example fails with:-
```
2022/01/11 11:55:18 Failed to read configuration from /config/storage.jsonnet: rpc error: code = Unknown desc = Failed to unmarshal configuration: proto: (line 2:4): unknown field "allowAcUpdatesForInstanceNamePrefixes"
```

If I try and use the lastest images from the registry for example `buildbarn/bb-browser:20211222T121123Z-547095c`

You get things like:-

```
2022/01/11 09:38:59 Failed to create authorizer: rpc error: code = InvalidArgument desc = Authorizer configuration not specified
```

So neither current k8s deployments as per the repo, nor will moving to the latest containers will work OOTB right now.

I have tried to figure out what the configs would be (I am a k8s infra person not a golang person) but I cannot work it out. Tried to add some things but `contentAddressableStorageAuthorizers` which I added to common configMap and included in browser configMap for example isn't used by the browser component etc.

Any pointers would be helpful.

Many thanks.
