### ISSUE TITLE
Use the new `rbe_configs_gen` script to create configs instead of `rbe_autoconfig`

### ISSUE THREAD

**Issue by finn-ball** [buildbarn/bb-deployments#57]
Seems `rbe_autoconfig` is getting depreciated in favour of a new script:
https://github.com/bazelbuild/bazel-toolchains#where-is-rbe_autoconfig

We should update the instructions to reflect this.

**Comment by moroten** [comment]
PR for using or describing `rbe_config_gen` is welcome. Relates to #19.

Currently using https://github.com/catthehacker/docker_images instead in the deployment examples. Closing for now.
