### ISSUE TITLE
Default bare configurations are not able to start `bb-storage`

### ISSUE THREAD

**Issue by Andrius-B** [buildbarn/bb-deployments#64]
I tried running the bare configurations and it seems that they fail to start up as the configurations have been updated to work with newer releases but the binaries were not were not (for example `bb-storage` is trying to build from a commit thats more than a year old).
I tried updating the `bb-storage` & other repository versions in WORKSPACE.bazel but that fails with strange patching errors.
Maybe this would be a good time to rethink the process, for example instead of using bazel to build all the parts, make a github action to build `master` / `release` versions of the different binaries (`bb-storage`, `bb-browser`, etc.) so they don't need to be rebuilt to run in this example setup?
In essence this is what happens with the docker / k8s setup - the images are not built, but rather pulled in from the image registries.

**Comment by moroten** [comment]
There is a CI test on the bare deployment. Maybe this issue is stale. Please comment if it is still a problem.
