### ISSUE TITLE
Config value 'rbe-ubuntu16-04' is not defined in any .rc file

### ISSUE THREAD

**Issue by mxHoward** [buildbarn/bb-deployments#67]
Hi,

I tried to get started with the Recommended Setup:
1. clone the repo to local;
2. run the `run.sh` bash;
3. create a `.bazelrc` file;
4. execute `bazel build` command;

And I got this error:
`ERROR: Config value 'rbe-ubuntu-16-04' is not defined in any .rc file`

Contents of `.bazelrc` file:
```
build:mycluster --remote_executor=grpc://localhost:8980
build:mycluster --remote_instance_name=remote-execution

build:mycluster-ubuntu16-04 --config=mycluster
build:mycluster-ubuntu16-04 --config=rbe-ubuntu16-04
build:mycluster-ubuntu16-04 --jobs=64
```

Output of the `run.sh` script:
![image](https://user-images.githubusercontent.com/30524316/165438645-3725d80e-244f-4c08-be91-f5580ed5717d.png)

My bazel version: 5.1.1
My OS info: Ubuntu 18.04 x86_64

Am I missing something out? Thanks in advance!!

**Comment by moroten** [comment]
The readme first states `cp bazelrc .bazelrc`. The errors you see is only during startup and should stop when everything is up and listening.

Anyway, I have started a work to bump to Ubuntu 22.04. Don't know if I'll manage to finish it today or if it will arrive next week.

Thank you for reporting!

**Comment by mxHoward** [comment]
Thank you for answering!

Turns out I forget to copy the `bazelrc` content to `.bazelrc`.

Thank you again!
