### ISSUE TITLE
Bazel builds on Buildbarn/K8s hanging indefinitely

### ISSUE THREAD

**Issue by bcspragu** [buildbarn/bb-deployments#87]
Hi there,

I've set up Buildbarn on a bare metal K8s cluster (running [Talos](https://www.talos.dev/)), using [Rook](https://rook.io/) for the underlying `PersistentVolumeClaim`s. The behavior I'm seeing is that is that remote builds against this build farm instance will get to a certain point, and then just freeze, e.g:

```plaintext
$ bazel build --config=remote-local //some/target

...

[56 / 411] 3 actions, 0 running
    GoLink nogo_actual_/nogo_actual [for tool]; 10459s remote
    Compiling src/google/protobuf/compiler/main.cc [for tool]; 10459s remote
    GoLink external/io_bazel_rules_go/go/tools/builders/go-protoc-bin_/go-protoc-bin [for tool]; 10459s remote
```

I originally thought it was a result of the Rook storage being slow, but I independently benchmarked that and found it was plenty fast (100+ MB/s). My next guess was that the volumes didn't have enough storage space, but those looked fine as well:

```plaintext
/dev/rbd1                    49G  3.4G   46G   7% /storage-cas
/dev/rbd0                   2.0G  588K  1.9G   1% /storage-ac
```

I made some minor changes to the given `storage.yaml`, but nothing that I'd expect to cause this:

```plaintext
$ git diff storage.yaml
diff --git a/kubernetes/storage.yaml b/kubernetes/storage.yaml
index 68a0cfe..41f58c2 100644
--- a/kubernetes/storage.yaml
+++ b/kubernetes/storage.yaml
@@ -62,17 +62,19 @@ spec:
     spec:
       accessModes:
       - ReadWriteOnce
+      storageClassName: rook-ceph-block
       resources:
         requests:
-          storage: 12Gi
+          storage: 50Gi
   - metadata:
       name: ac
     spec:
       accessModes:
       - ReadWriteOnce
+      storageClassName: rook-ceph-block
       resources:
         requests:
-          storage: 1Gi
+          storage: 2Gi
```

And lowered the replica count on the workers, as I was crashing my dusty old servers (I'm currently running 3 nodes):

```plaintext
$ git diff worker-ubuntu22-04.yaml
diff --git a/kubernetes/worker-ubuntu22-04.yaml b/kubernetes/worker-ubuntu22-04.yaml
index bbec852..59929f3 100644
--- a/kubernetes/worker-ubuntu22-04.yaml
+++ b/kubernetes/worker-ubuntu22-04.yaml
@@ -7,7 +7,7 @@ metadata:
     prometheus.io/port: "80"
     prometheus.io/scrape: "true"
 spec:
-  replicas: 8
+  replicas: 3

```

<details>
<summary>.bazelrc</summary>

```plaintext
build:remote --remote_download_toplevel
build:remote --dynamic_mode=off
build:remote --jobs=3
build:remote --extra_execution_platforms=//tools/remote-toolchains:ubuntu-act-22-04-platform
# build:remote --extra_toolchains=//tools/remote-toolchains:all

build:remote-local --config=remote
build:remote-local --remote_executor=grpc://192.168.5.2:8980

build:remote-ci --config=remote
build:remote-ci --remote_executor=grpc://10.98.227.156:8980
```

</details>

<details>
<summary>Scheduler screenshots</summary>

![Screenshot 2023-03-08 at 18-32-44 Buildbarn Scheduler](https://user-images.githubusercontent.com/2402010/223900952-0e6c31f9-ab23-4e7a-87ba-cafdbd2fe824.png)

![Screenshot 2023-03-08 at 18-32-57 Buildbarn Scheduler](https://user-images.githubusercontent.com/2402010/223900951-c97f484d-7bdc-4bee-a0b3-760000659dad.png)

![Screenshot 2023-03-08 at 18-33-11 Buildbarn Scheduler](https://user-images.githubusercontent.com/2402010/223900946-e6d407c2-3366-4fb1-b87f-6bb9afd2f187.png)

</details>

Any ideas?

**Comment by EdSchouten** [comment]
Hey! My recommendation would be to look at these two things:
- The Prometheus metrics for `grpc_*`. Maybe Bazel is simply calling RPCs against your cluster that fail with a transient error, causing it to retry.
- Enable [the `active_spans` option](https://github.com/buildbarn/bb-storage/blob/462adbbf619f0db373d635246db5fb787ced1ef9/pkg/proto/configuration/global/global.proto#L261), and visit `/active_spans` on the frontend, scheduler, storage, processes. That way you can see which RPCs are in flight.

**Comment by bcspragu** [comment]
Following up on this, I integrated the frontend/scheduler/storage/browser into Prometheus, here's a graph of all the non-OK gRPC endpoints that fire when I attempt a build against the cluster:

![image](https://user-images.githubusercontent.com/2402010/226742988-1bb8ebe5-0262-4847-9580-80a2c4dba173.png)


I'm guessing all the `Canceled/DeadlineExceeded/Unavailable` errors are relevant. Also, the past few times I've run it, instead of hanging, it eventually fails with something like:


```
ERROR: /home/bsprague/.cache/bazel/_bazel_bsprague/549063a402dbea3e5c363fba08c6dd05/external/com_google_protobuf/BUILD.bazel:457:10: Compiling src/google/protobuf/compiler/main.cc [for tool] failed: (Exit 34): 6 errors during bulk transfer:
java.io.IOException: Error while uploading artifact with digest '80b91e14fe3ceb040aaad6cba19c1ebfe39293bb5c2687f156b92c15bdf19349/26097560'
java.io.IOException: Error while uploading artifact with digest
[... repeated a few more times ...]
com.google.devtools.build.lib.remote.common.BulkTransferException: 6 errors during bulk transfer:
java.io.IOException: Error while uploading artifact with digest '80b91e14fe3ceb040aaad6cba19c1ebfe39293bb5c2687f156b92c15bdf19349/26097560'
java.io.IOException: Error while uploading artifact with digest 'af535d2e08a1d6f3f0ab53a59a5cc3f0f62f3962a9c94ef8927f2e3ad2f8bf36/70156984'
[... repeated a few more times ...]
        at com.google.devtools.build.lib.remote.util.RxUtils$BulkTransferExceptionCollector.onResult(RxUtils.java:91)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableCollectSingle$CollectSubscriber.onNext(FlowableCollectSingle.java:94)
        at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapPublisher$SingleFlatMapPublisherObserver.onNext(SingleFlatMapPublisher.java:107)
[... ginormous stack trace ...]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
        Suppressed: java.io.IOException: Error while uploading artifact with digest '80b91e14fe3ceb040aaad6cba19c1ebfe39293bb5c2687f156b92c15bdf19349/26097560'
                at com.google.devtools.build.lib.remote.ByteStreamUploader.lambda$uploadBlobAsync$0(ByteStreamUploader.java:172)
                at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:203)
                at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:190)
                at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:133)
                ... 47 more
        Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 59.999951391s. [closed=[], committed=[buffered_nanos=69282, remote_addr=192.168.5.2/192.168.5.2:8980]]
                at io.grpc.Status.asRuntimeException(Status.java:535)
                ... 10 more
        Suppressed: java.io.IOException: Error while uploading artifact with digest 'af535d2e08a1d6f3f0ab53a59a5cc3f0f62f3962a9c94ef8927f2e3ad2f8bf36/70156984'
[... more of the same ...]
```

I've tried a few `bazel clean --config=remote`s as well, but the same happens.

**Comment by moroten** [comment]
The 59.9999s timeout looks suspiciously close to the default [--remote_timeout](https://bazel.build/reference/command-line-reference#flag--remote_timeout) which is 60s. If a blob cannot be uploaded within that time frame, that blob is restarted from first byte again.

**Comment by bcspragu** [comment]
That's a good lead, thanks! That said, it seems like it may be masking some other problem. The artifact in question seems to be some part of the protobuf compiler, which I wouldn't expect to be too big. Even if we're talking about transmitting between my machine and the build cluster, that should all be happening over a local network (e.g. not bandwidth/latency constrained), and the machines on both ends should be plenty powerful.

I can up the time limit and see what happens, but my suspicion is I'll just hit whatever I set the new time limit too

**Comment by moroten** [comment]
Also give [--slim_profile=false](https://bazel.build/reference/command-line-reference#flag--slim_profile) [--profile=profile.json](https://bazel.build/reference/command-line-reference#flag--profile) and [--experimental_remote_grpc_log=something.grpc-log](https://bazel.build/reference/command-line-reference#flag--experimental_remote_grpc_log) a try. The profile can be opened in in `chrome://tracing` and grpc log can [be pretty printed](https://github.com/bazelbuild/tools_remote#printing-grpc-log-files).

**Comment by EdSchouten** [comment]
Do keep in mind that Bazel's default value of `--remote_timeout` is set far too aggressive. The issue is that if you run Bazel with a high `-j` / `--jobs`, it also increases the parallelism used to upload files. It's not uncommon for Bazel to perform more than a thousand Write() calls in parallel. When that happens, Bazel is basically competing with itself for bandwidth, meaning that it doesn't become unlikely that you hit the 60 second timeout.

**Comment by moroten** [comment]
Closing as stale.
