### ISSUE TITLE
buildbarn configuration of goma

### ISSUE THREAD

**Issue by qinjidong** [buildbarn/bb-deployments#96]
Hello developer,
  Is there a wizard that can show me how to connect buildbarn with goma (remoteexec_proxy) please?

Best Regards

**Comment by EdSchouten** [comment]
Hey! I asked around on Slack whether anyone had any experience. Nobody seemingly responded.

If you did manage to figure this out, be sure to share your findings. This makes life easier for the next person.

**Comment by stagnation** [comment]
We have ongoing work to help other build systems in here: https://github.com/buildbarn/bb-deployments/pull/95
I'd be happy to add Goma to that.

**Comment by stagnation** [comment]
Hi Again

I could not get `goma` to work with `Buildbarn`, it should work - but I get http errors from weird servers/endpoints
and this is not my forte. The configuration to proxy from `goma server` to `Buildbarn` is simple and can be reused. But I could not set up the `goma client` to work.

I wrote some notes here that I hope will speed up development if we make another attempt,
and maybe someone with more experience can spot my errors.
https://github.com/stagnation/bb-deployments/blob/feature/do-not-merge-failed-goma-attempt/goma-failed-attempt.rst

**Comment by qinjidong** [comment]
Hi Stagnation,

I read the steps you wrote, there are some trouble in Goma's authentication.
Try to avoid use goma auth may make things easier.
Follow the steps of https://github.com/bromite/bromite/discussions/1032 can avoid goma auth.

Best Regards

**Comment by stagnation** [comment]
Thanks for the help! I will try that.

**Comment by qinjidong** [comment]
Hi,

I cannot connect remoteexec_proxy to bb_storage. 
What **remoteexec-addr** should I use in remoteexec_proxy's command line?

**Referring to buildgrid, I use the following command line to start remoteexec_proxy.**
go run cmd/remoteexec_proxy/main.go -port 7979 -insecure-remoteexec -remoteexec-addr localhost:7980 -remote-instance-name default --exec-config-file config_file

**Config file of buildgrid.**
server:
  - !channel
    port: 7980
    insecure-mode: true
...

**Comment by EdSchouten** [comment]
Hey @qinjidong,

I saw on Slack that you managed to get it working now. Just to help out others in the future, would you be willing to share the configs you used in this ticket? Be sure to close the issue afterwards. Thanks!

**Comment by qinjidong** [comment]
I mainly encountered the following two problems during the adaptation process.

1. connect remoteexec_proxy to bb_storage
-> remoteexec_proxy needs a -platform-container-image as well.
-> like this:
goma/server $ go run \
    cmd/remoteexec_proxy \
...
    -platform-container-image 'docker://ghcr.io/catthehacker/ubuntu:act-22.04@sha256:5f9c35c25db1d51a8ddaae5c0ba8d3c163c5e9a4a6cc97acd409ac7eae239448' 

2. Upload the toolchain to bb_worker, then run it inside docker. Because I need do cross compile, while the toolchain path is fixed.
-> docker cp {toolchain} docker-compose_runner-fuse-ubuntu22-04_1:{toolchain_path}

**Comment by EdSchouten** [comment]
Thanks!
